from schemas.activity_schemas.activity_bookings import ActivityBookingDetailedSchema, ActivityBookingSchema
from schemas.activity_schemas.activity import ActivityDetailSchema, ActivitySchema

from schemas.base_schemas.base_hotel_booking import BaseHotelBookingSchema
from schemas.base_schemas.base_name_img_info import BaseNameImgInfoSchema
from schemas.base_schemas.base_hotel import BaseHotelSchema

from schemas.hotels.partner_hotels.partner_hotel_schema import PartnerHotelSchema, PartnerHotelDetailedSchema
from schemas.hotels.partner_hotels.partner_hotel_booking_schema import PartnerHotelBookingDetailedSchema, PartnerHotelBookingSchema

from schemas.hotels.we_hotels.we_hotel_booking_schema import WeHotelBookingDetailedSchema, WeHotelBookingSchema
from schemas.hotels.we_hotels.we_hotel_discount_schema import WeHotelDiscountDetailSchema, WeHotelDiscountSchema
from schemas.hotels.we_hotels.we_hotel_leadtime_schema import WeHotelLeadtimesDetailSchema, WeHotelLeadtimesSchema
from schemas.hotels.we_hotels.we_hotel_room_booking_schema import WeHotelRoomBookingDetailedSchema, WeHotelRoomBookingSchema
from schemas.hotels.we_hotels.we_hotel_room_hold_schema import WeHotelRoomHoldSchema, WeHotelRoomHoldDetailedSchema
from schemas.hotels.we_hotels.we_hotel_room_rate_schema import WeHotelRoomRateDescriptiveSchema, WeHotelRoomRateSchema
from schemas.hotels.we_hotels.we_hotel_room_schema import WeHotelRoomSchema, WeHotelRoomDetailedSchema
from schemas.hotels.we_hotels.we_hotel_schema import WeHotelSchema, WeHotelDetailedSchema

from schemas.events import EventDescriptionSchema, EventSchema

from schemas.park_img import ParkImgDetailedSchema, ParkImgSchema

from schemas.park import ParkDetailSchema, ParkSchema