"""update site model

Revision ID: 103563a99a82
Revises: 7ca81685511f
Create Date: 2026-07-02 12:16:27.490527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '103563a99a82'
down_revision = '7ca81685511f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
