"""update blog model to handle posting and patching logic

Revision ID: 1a1e3a96f4b7
Revises: dbc83803284b
Create Date: 2026-07-04 12:05:07.927836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1e3a96f4b7'
down_revision = 'dbc83803284b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('edited_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blogs', schema=None) as batch_op:
        batch_op.drop_column('edited_at')
        batch_op.drop_column('published_at')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
