"""latest migrations

Revision ID: 231d61d0028f
Revises: 
Create Date: 2026-09-23 11:42:04.874179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231d61d0028f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('all_year_round', sa.Boolean(), nullable=False),
    sa.Column('available_months', sa.JSON(), nullable=True),
    sa.Column('free_with_stay', sa.Boolean(), nullable=False),
    sa.Column('discount_with_stay', sa.Boolean(), nullable=True),
    sa.Column('stay_discount', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('park_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], name=op.f('fk_activities_park_id_parks')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('multi_day_event', sa.Boolean(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('no_of_tickets', sa.Integer(), nullable=False),
    sa.Column('tickets_sold', sa.Integer(), nullable=False),
    sa.Column('tickets_remaining', sa.Integer(), nullable=False),
    sa.Column('ticket_price', sa.Integer(), nullable=False),
    sa.Column('park_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], name=op.f('fk_events_park_id_parks')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('park_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], name=op.f('fk_hotels_park_id_parks')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('park_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('park_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], name=op.f('fk_park_image_park_id_parks')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('no_of_rooms', sa.Integer(), nullable=False),
    sa.Column('max_people', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_rooms_hotel_id_hotels')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('img')
    )
    op.create_table('walking_trail_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map', sa.String(), nullable=False),
    sa.Column('code_of_conduct', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['activities.id'], name=op.f('fk_walking_trail_model_id_activities')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('percentage_off', sa.Float(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('discount_based_on_booking', sa.Boolean(), nullable=False),
    sa.Column('booking_start_date', sa.Date(), nullable=True),
    sa.Column('booking_end_date', sa.Date(), nullable=True),
    sa.Column('stay_start_date', sa.Date(), nullable=True),
    sa.Column('stay_end_date', sa.Date(), nullable=True),
    sa.Column('is_hotel_wide_discount', sa.Boolean(), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_discounts_hotel_id_hotels')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_discounts_room_id_rooms')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('modifier_type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], name=op.f('fk_room_rates_hotel_id_hotels')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_rates_room_id_rooms')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_rates')
    op.drop_table('discounts')
    op.drop_table('walking_trail_model')
    op.drop_table('rooms')
    op.drop_table('park_image')
    op.drop_table('hotels')
    op.drop_table('events')
    op.drop_table('activities')
    op.drop_table('parks')
    # ### end Alembic commands ###
