"""add activity tables

Revision ID: 234536491953
Revises: fb761da2f600
Create Date: 2026-09-21 15:13:41.074383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234536491953'
down_revision = 'fb761da2f600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('all_year_round', sa.Boolean(), nullable=False),
    sa.Column('available_months', sa.JSON(), nullable=True),
    sa.Column('free_with_stay', sa.Boolean(), nullable=False),
    sa.Column('discount_with_stay', sa.Boolean(), nullable=False),
    sa.Column('stay_discount', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('park_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], name=op.f('fk_activities_park_id_parks')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('walking_trail_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map', sa.String(), nullable=False),
    sa.Column('code_of_conduct', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['activities.id'], name=op.f('fk_walking_trail_model_id_activities')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('walking_trail_model')
    op.drop_table('activities')
    # ### end Alembic commands ###
