"""initial migration

Revision ID: 351504e04e1a
Revises: 
Create Date: 2026-07-03 13:31:38.717268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '351504e04e1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.Column('endangered_level', sa.String(), nullable=False),
    sa.Column('animal_type', sa.String(), nullable=False),
    sa.Column('big_five', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('intro', sa.String(), nullable=False),
    sa.Column('head_img', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.Column('primary_img_1', sa.String(), nullable=False),
    sa.Column('primary_img_2', sa.String(), nullable=False),
    sa.Column('primary_img_3', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('site_animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], name=op.f('fk_site_animals_animal_id_animals')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_site_animals_site_id_sites')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_animals')
    op.drop_table('sites')
    op.drop_table('animals')
    # ### end Alembic commands ###
