"""initial migration

Revision ID: 6628de58d74c
Revises: 
Create Date: 2026-09-24 14:40:14.356616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6628de58d74c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('all_year_round', sa.Boolean(), nullable=False),
    sa.Column('available_months', sa.JSON(), nullable=True),
    sa.Column('free_with_stay', sa.Boolean(), nullable=False),
    sa.Column('discount_with_stay', sa.Boolean(), nullable=False),
    sa.Column('stay_discount', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('park_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], name=op.f('fk_activities_park_id_parks')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('multi_day_event', sa.Boolean(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('no_of_tickets', sa.Integer(), nullable=False),
    sa.Column('tickets_sold', sa.Integer(), nullable=False),
    sa.Column('tickets_remaining', sa.Integer(), nullable=False),
    sa.Column('ticket_price', sa.Integer(), nullable=False),
    sa.Column('park_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], name=op.f('fk_events_park_id_parks')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('park_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('park_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], name=op.f('fk_park_image_park_id_parks')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('partner_hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('park_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], name=op.f('fk_partner_hotels_park_id_parks')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('wildenterprise_hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('park_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], name=op.f('fk_wildenterprise_hotels_park_id_parks')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_ref', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('guests', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('date_of_deposit_charge', sa.Date(), nullable=False),
    sa.Column('date_of_remainder_charge', sa.Date(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['wildenterprise_hotels.id'], name=op.f('fk_bookings_hotel_id_wildenterprise_hotels')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_ref')
    )
    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('no_of_rooms', sa.Integer(), nullable=False),
    sa.Column('max_people', sa.Integer(), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['wildenterprise_hotels.id'], name=op.f('fk_rooms_hotel_id_wildenterprise_hotels')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('img')
    )
    op.create_table('walking_trail_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('map', sa.String(), nullable=False),
    sa.Column('code_of_conduct', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['activities.id'], name=op.f('fk_walking_trail_model_id_activities')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_reference', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('no_of_people', sa.Integer(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('hotel_booking_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name=op.f('fk_activity_booking_activity_id_activities')),
    sa.ForeignKeyConstraint(['hotel_booking_id'], ['bookings.id'], name=op.f('fk_activity_booking_hotel_booking_id_bookings')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_reference')
    )
    op.create_table('discounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('percentage_off', sa.Float(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('discount_based_on_booking', sa.Boolean(), nullable=False),
    sa.Column('booking_start_date', sa.Date(), nullable=True),
    sa.Column('booking_end_date', sa.Date(), nullable=True),
    sa.Column('stay_start_date', sa.Date(), nullable=True),
    sa.Column('stay_end_date', sa.Date(), nullable=True),
    sa.Column('is_hotel_wide_discount', sa.Boolean(), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['wildenterprise_hotels.id'], name=op.f('fk_discounts_hotel_id_wildenterprise_hotels')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_discounts_room_id_rooms')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lead_time_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('min_days', sa.Integer(), nullable=False),
    sa.Column('max_days', sa.Integer(), nullable=True),
    sa.Column('multiplier', sa.Float(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['wildenterprise_hotels.id'], name=op.f('fk_lead_time_rules_hotel_id_wildenterprise_hotels')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_lead_time_rules_room_id_rooms')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('price_locked', sa.Float(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_room_bookings_booking_id_bookings')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_bookings_room_id_rooms')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_holds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('arrival_date', sa.Date(), nullable=False),
    sa.Column('departure_date', sa.Date(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_holds_room_id_rooms')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('modifier_type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['wildenterprise_hotels.id'], name=op.f('fk_room_rates_hotel_id_wildenterprise_hotels')),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], name=op.f('fk_room_rates_room_id_rooms')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('room_rates')
    op.drop_table('room_holds')
    op.drop_table('room_bookings')
    op.drop_table('lead_time_rules')
    op.drop_table('discounts')
    op.drop_table('activity_booking')
    op.drop_table('walking_trail_model')
    op.drop_table('rooms')
    op.drop_table('bookings')
    op.drop_table('wildenterprise_hotels')
    op.drop_table('partner_hotels')
    op.drop_table('park_image')
    op.drop_table('events')
    op.drop_table('activities')
    op.drop_table('parks')
    # ### end Alembic commands ###
