"""initial migration

Revision ID: 7ca81685511f
Revises: 
Create Date: 2026-07-02 11:32:29.075159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca81685511f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('intro', sa.String(), nullable=False),
    sa.Column('head_img', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.Column('primary_img_1', sa.String(), nullable=False),
    sa.Column('primary_img_2', sa.String(), nullable=False),
    sa.Column('primary_img_3', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sites')
    # ### end Alembic commands ###
