"""create site animals database

Revision ID: c25dda965585
Revises: 4ea2e04ba95d
Create Date: 2026-07-03 10:34:01.042276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c25dda965585'
down_revision = '4ea2e04ba95d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_animals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], name=op.f('fk_site_animals_animal_id_animals')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_site_animals_site_id_sites')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_animals')
    # ### end Alembic commands ###
