"""create site blogs database

Revision ID: dbc83803284b
Revises: 351504e04e1a
Create Date: 2026-07-04 11:10:41.265484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbc83803284b'
down_revision = '351504e04e1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blogs.id'], name=op.f('fk_site_blogs_blog_id_blogs')),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], name=op.f('fk_site_blogs_site_id_sites')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_blogs')
    # ### end Alembic commands ###
