"""add event table

Revision ID: fb761da2f600
Revises: 17da0b5f9157
Create Date: 2026-09-19 14:33:38.321659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb761da2f600'
down_revision = '17da0b5f9157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('multi_day_event', sa.Boolean(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('no_of_tickets', sa.Integer(), nullable=False),
    sa.Column('tickets_sold', sa.Integer(), nullable=False),
    sa.Column('tickets_remaining', sa.Integer(), nullable=False),
    sa.Column('ticket_price', sa.Integer(), nullable=False),
    sa.Column('park_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=False),
    sa.Column('info', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], name=op.f('fk_events_park_id_parks')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
